---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ci-butler-certs
  namespace: ci-butler-ns

spec:
  secretName: ci-butler-tls
  commonName: "ci-butler.news.dev.nyt.net"
  dnsNames:
  - "ci-butler.news.dev.nyt.net"
  - "*.ci-butler.news.dev.nyt.net"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
