---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: notequalia-user
secrets:
  - name: "}YOR]~kc/?]DB@q%|"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notequalia-io.fullname" . }}-web
spec:
  serviceAccountName: notequalia-user
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notequalia-io.name" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "notequalia-io.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        # kubernetes.io/hostname=pool-cognodes
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pool-cognodes

          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pool-cognodes

      initContainers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: check-installation
        command: ['/venv/bin/notequalia-io', 'check']
        envFrom:
          - configMapRef:
              name: {{ include "notequalia-io.fullname" . }}-env

      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: check-db-connection
        command: ['/venv/bin/notequalia-io', 'check-db']
        envFrom:
          - configMapRef:
              name: {{ include "notequalia-io.fullname" . }}-env

      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: run-database-migrations
        command: ['/venv/bin/notequalia-io', 'migrate-db']
        envFrom:
          - configMapRef:
              name: {{ include "notequalia-io.fullname" . }}-env
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "notequalia-io.fullname" . }}-secrets
              key: postgresql-password

        env:
        - name: DOCKER_IMAGE
          value: {{ .Values.image.tag }}

      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: purge-sessions
        command: ['/venv/bin/notequalia-io', 'purge-sessions']
        envFrom:
          - configMapRef:
              name: {{ include "notequalia-io.fullname" . }}-env

      volumes:
        - name: notequalia-uploads-volume
          persistentVolumeClaim:
            claimName: pvc-notequalia-io

      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-web-application-server
        command: ['/venv/bin/notequalia-io', 'web']
        livenessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 30
          periodSeconds: 150
        readinessProbe:
          httpGet:
            path: /health
            port: api
          initialDelaySeconds: 1

        env:
          - name: UPLOAD_FOLDER
            value: /notequalia.io/file-uploads
          # - name: OAUTH2_CLIENT_SECRET
          #   valueFrom:
          #     secretKeyRef:
          #       name: {{ template "notequalia-io.fullname" . }}-secrets
          #       key: oauth2-client-secret

        envFrom:
          - configMapRef:
              name: {{ include "notequalia-io.fullname" . }}-env

        ports:
        - containerPort: 5000
          name: api

        volumeMounts:
          - name: notequalia-uploads-volume
            mountPath: /notequalia.io
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: notequalia-operator
# spec:
#   replicas: 1
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       application: notequalia-operator
#   template:
#     metadata:
#       labels:
#         application: notequalia-operator
#     spec:
#       serviceAccountName: default
#       containers:
#       - name: notequalia-k8s-operator
#         image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#         imagePullPolicy: {{ .Values.image.pullPolicy }}
#         command: ['/venv/bin/notequalia-io', 'k8s']
#         envFrom:
#           - configMapRef:
#               name: {{ include "notequalia-io.fullname" . }}-env
