{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "notequalia-io.fullname" . }}-ingress-cognod-es
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "600"
    # kubernetes.io/tls-acme: 'true'
    # https://docs.giantswarm.io/guides/advanced-ingress-configuration/#custom-max-body-size
spec:
  tls:
  - hosts:
    - cognod.es
    - api.cognod.es
    - app.cognod.es
    - data.cognod.es
    - mail.cognod.es
    secretName: cognod-es-letsencrypt-secret
  rules:
  - host: cognod.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "notequalia-io.fullname" . }}
          servicePort: 5000
  - host: api.cognod.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "notequalia-io.fullname" . }}
          servicePort: 5000
  - host: data.cognod.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "notequalia-io.fullname" . }}
          servicePort: 5000
  - host: app.cognod.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "notequalia-io.fullname" . }}
          servicePort: 5000
  - host: mail.cognod.es
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "notequalia-io.fullname" . }}
          servicePort: 5000
{{- end }}

# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: {{ include "notequalia-io.fullname" . }}-ingress-wavemandala
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: "letsencrypt-staging"
#     nginx.ingress.kubernetes.io/proxy-body-size: 8m
#     kubernetes.io/tls-acme: 'true'
#     # https://docs.giantswarm.io/guides/advanced-ingress-configuration/#custom-max-body-size
# spec:
#   tls:
#   - hosts:
#     - wavemanda.la
#     secretName: wavemandala-roots
#   rules:
#   - host: wavemanda.la
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: {{ include "notequalia-io.fullname" . }}
#           servicePort: 5000
# ---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: {{ include "notequalia-io.fullname" . }}-ingress-notequalia
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: "letsencrypt-staging"
#     nginx.ingress.kubernetes.io/proxy-body-size: 8m
#     kubernetes.io/tls-acme: 'true'
#     # https://docs.giantswarm.io/guides/advanced-ingress-configuration/#custom-max-body-size
# spec:
#   tls:
#   - hosts:
#     - notequalia.io
#     secretName: notequalia-roots
#   rules:
#   - host: notequalia.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: {{ include "notequalia-io.fullname" . }}
#           servicePort: 5000
# ---
