# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: {{ include "cognodes-io.fullname" . }}-worker
# spec:
#   template:
#     spec:
#       containers:
#       - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#         imagePullPolicy: {{ .Values.image.pullPolicy }}
#         name: {{ .Chart.Name }}-worker
#         command: ['/venv/bin/cognodes-io', 'worker']
#         envFrom:
#           - configMapRef:
#               name: {{ include "cognodes-io.fullname" . }}-env

#       restartPolicy: Never
#   backoffLimit: 6 # number of retries before throwing error
#   completions: 6 # number of times to run
#   parallelism: 2 # number of pods that can run in parallel
#   activeDeadlineSeconds: 60 # time to allow job to run
