{{- if .Values.rodrivamp.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rodrivamp-ghost-blog
spec:

  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: rodrivamp-ghost-blog
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rodrivamp-ghost-blog
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - pool-cognodes-361bh

      containers:
      - name: blog
        image: ghost:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 2368
        env:
        - name: url
          value: https://rodrivamp.com
        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: rodrivamp-content
      volumes:
        - name: rodrivamp-content
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rodrivamp-ghost-blog
  labels:
    app.kubernetes.io/name: rodrivamp-ghost-blog
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: NodePort
  ports:
    - port: 2368
      targetPort: 2368
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: rodrivamp-ghost-blog
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "notequalia-io.fullname" . }}-ingress-rodrivamp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 800m
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "600"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # kubernetes.io/tls-acme: 'false'
    # https://docs.giantswarm.io/guides/advanced-ingress-configuration/#custom-max-body-size
spec:
  tls:
  - hosts:
    - rodrivamp.com
    - admin.rodrivamp.com
    - contato.rodrivamp.com
    secretName: rodrivamp-letsencrypt-secret
  rules:
  - host: rodrivamp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rodrivamp-ghost-blog
          servicePort: 2368
  - host: admin.rodrivamp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rodrivamp-ghost-blog
          servicePort: 2368
  - host: contato.rodrivamp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rodrivamp-ghost-blog
          servicePort: 2368
{{- end }}
