---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "notequalia-io.fullname" . }}-secrets
  labels:
{{ include "notequalia-io.labels" . | indent 4 }}
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  ngrok-token: {{ .Values.ngrok.token | b64enc | quote }}
  google-client-id: {{ .Values.authlib.google_client_id | b64enc | quote }}
  google-client-secret: {{ .Values.authlib.google_client_secret | b64enc | quote }}
