---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notequalia-io.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "notequalia-io.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "notequalia-io.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
