---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationauthusers.cognod.es
spec:
  scope: Namespaced
  group: cognod.es
  names:
    kind: ApplicationAuthUser
    plural: applicationauthusers
    singular: applicationauthuser
    shortNames:
      - nqluser
      - nqlusr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
