---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: notequalia-k8sns
  name: notequalia-k8sns
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: notequalia-user
secrets:
  - name: ngrok-token
