name: 🚢 K8S Docker Image

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: K8S Docker Image (Kubernetes Deployment)
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gabrielfalcao/k8s-notequalia-io
        # tag_with_ref: false  # prevent pushing "latest" tag
        tag_with_sha: true
        dockerfile: Dockerfile
        tags: "${{ github.sha }}"
