name: 🚢 K8S Docker Image

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DATABASE: test
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: K8S Docker Image (Kubernetes Deployment)
      uses: docker/build-push-action@v1.1.0
      env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: test
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gabrielfalcao/k8s-notequalia-io
        # tag_with_ref: false  # prevent pushing "latest" tag
        tag_with_sha: true
        dockerfile: Dockerfile
        tags: "${{ github.sha }}"
